# Generated by Django 2.0.7 on 2018-08-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uat',
            name='message',
            field=models.TextField(default='No message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uat',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
