# Generated by Django 2.0.7 on 2018-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testboxes', '0002_auto_20180816_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='uat',
            name='prefix',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
