# Generated by Django 2.0.7 on 2018-08-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testboxes', '0004_uat_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uat',
            name='running',
        ),
    ]
