# Generated by Django 2.0.7 on 2018-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testboxes', '0005_remove_uat_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='uat',
            name='taskid',
            field=models.TextField(default=''),
        ),
    ]
