# Generated by Django 2.0.7 on 2018-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testboxes', '0006_uat_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='message',
            field=models.TextField(default='No Message'),
        ),
        migrations.AddField(
            model_name='qa',
            name='prefix',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='qa',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qa',
            name='taskid',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='uat',
            name='message',
            field=models.TextField(default='No Message'),
        ),
        migrations.AlterField(
            model_name='uat',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uat',
            name='taskid',
            field=models.TextField(default='None'),
        ),
    ]
